name: cirunnam

on:
  push:
    branches: [ 'cinam' ]
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: ssh execute remote to vm
        run: |
          set -x
          #TODO setup sshprivatekey
          #TODO set auto accept ip fingerprint ie -o StrictHostKeyChecking=no     
          ssh nam@34.124.143.147
