name: CI

on:
  push:
    branches: [ "cinam" ]
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo 122
          echo 333
          echo 4444
